sudo: false
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
cache: cargo
install:
- wget https://github.com/jedisct1/libsodium/releases/download/1.0.15/libsodium-1.0.15.tar.gz
- tar xvfz libsodium-1.0.15.tar.gz
- cd libsodium-1.0.15 && ./configure --prefix=$HOME/installed_libsodium && make && make install &&
  cd ..
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
script:
  - cargo test --features "hacl-star-resolver vector-tests" --verbose
  - cargo test --features "hacl-star-accelerated vector-tests" --verbose
  - cargo test --features "ring-resolver vector-tests" --verbose
  - cargo test --features "ring-accelerated vector-tests" --verbose
  - cargo test --features "libsodium-resolver vector-tests" --verbose
  - cargo test --features "libsodium-accelerated vector-tests" --verbose

