[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://snow.rs"
documentation = "https://snow.rs/doc/snow"
repository = "https://github.com/mcginty/snow"
version = "0.2.1"
authors = ["Jake McGinty <me@jake.su>", "trevp"]
license = "Unlicense"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto"]

[features]
default = ["default-resolver"]
nightly = ["blake2-rfc/simd_opt", "chacha20-poly1305-aead/simd_opt", "x25519-dalek/nightly"]
default-resolver = ["chacha20-poly1305-aead", "blake2-rfc", "rust-crypto", "x25519-dalek", "rand"]
hacl-star-resolver = ["hacl-star"]
hacl-star-accelerated = ["hacl-star-resolver", "default-resolver"]
ring-resolver = ["ring"]
ring-accelerated = ["ring-resolver", "default-resolver"]
libsodium-resolver = ["sodiumoxide"]
libsodium-accelerated = ["libsodium-resolver", "default-resolver"]
vector-tests = []

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "mcginty/snow", branch = "master" }
appveyor = { repository = "mcginty/snow", branch = "master", service = "github" }

[dependencies]
arrayref = "^0.3"
byteorder = "^1.2"
failure = "^0.1"
smallvec = "^0.6"
static_slice = "0.0.3"
x25519-dalek = { version = "^0.2", optional = true, default-features = false, features = ["std", "u64_backend"] }

chacha20-poly1305-aead = { version = "^0.1", optional = true }
blake2-rfc = { version = "^0.2", optional = true }
rust-crypto = { version = "^0.2", optional = true }
hacl-star = { version = "=0.0.11", optional = true }
rand = { version = "0.5.0-pre.2", optional = true }
ring = { version = "0.13.0-alpha5", optional = true }
#sodiumoxide = { version = "^0.1.0", optional = true } # We have to use concrete revision until version bump.
sodiumoxide = { git = "https://github.com/sodiumoxide/sodiumoxide", rev = "d01bbdbd91313453ae244d56973545d9b695af20", optional = true }

[dev-dependencies]
clap = "^2.0"
criterion = "0.2"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
hex = "^0.3"
lazy_static = "^1.0"

[build-dependencies]
rustc_version = "^0.2"

[package.metadata.docs.rs]
features = [ "ring-resolver", "hacl-star-resolver", "libsodium-resolver" ]
all-features = false
no-default-features = false

