[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://github.com/mcginty/snow"
repository = "https://github.com/mcginty/snow"
version = "0.1.9"
authors = ["Jake McGinty <me@jake.su>", "trevp"]
license = "Unlicense"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto"]

[features]
default = []
nightly = ["blake2-rfc/simd_opt", "chacha20-poly1305-aead/simd_opt"]
hacl-resolver = ["hacl-star", "arrayref"]
hacl-accelerated = ["hacl-resolver"]
ring-resolver = ["ring"]
ring-accelerated = ["ring", "ring-resolver"]
vector-tests = []

[badges]
travis-ci = { repository = "mcginty/snow", branch = "master" }

[dependencies]
arrayvec = "^0.4"
arrayref = { version = "0.3", optional = true }
error-chain = "^0.11"
rust-crypto = "^0.2"
byteorder = "^1.2"
rand = "^0.5"
static_slice = "0.0.3"
blake2-rfc = "^0.2"
chacha20-poly1305-aead = "^0.1"
hacl-star = { version = "=0.0.11", optional = true }
ring = { version = "0.13.0-alpha", optional = true }

[dev-dependencies]
clap = "^2.0"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
hex = "^0.2"
lazy_static = "^0.2"

[build-dependencies]
rustc_version = "^0.2"

[package.metadata.docs.rs]
features = [ "ring-resolver" ]
all-features = false
no-default-features = false

