[package]
name = "snow"
description = "A pure-rust implementation of the Noise Protocol Framework"
homepage = "https://snow.rs"
documentation = "https://snow.rs/doc/snow"
repository = "https://github.com/mcginty/snow"
version = "0.6.0-alpha2"
authors = ["Jake McGinty <me@jake.su>", "trevp"]
license = "Unlicense"
categories = ["cryptography"]
readme = "README.md"
keywords = ["noise", "protocol", "crypto"]
edition = "2018"

# This is slightly mumbo-jumboey, but in short:
# Features with a -resolver suffix simply enables the existence of a specific resolver,
# and -accelerated suffix means that this resolver will be the default used by the Builder.
[features]
default = ["default-resolver"]
nightly = ["blake2-rfc/simd_opt", "chacha20-poly1305-aead/simd_opt", "x25519-dalek/nightly", "subtle/nightly"]
default-resolver = ["chacha20-poly1305-aead", "blake2-rfc", "sha2", "x25519-dalek", "rand"]
hacl-star-resolver = ["hacl-star"]
hacl-star-accelerated = ["hacl-star-resolver", "default-resolver"]
ring-resolver = ["ring"]
ring-accelerated = ["ring-resolver", "default-resolver"]
vector-tests = []

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "mcginty/snow", branch = "master" }
appveyor = { repository = "mcginty/snow", branch = "master", service = "github" }

[dependencies]
arrayref = "0.3.5"
rand_core = "0.4"
subtle = "2.1"

# default crypto provider 
chacha20-poly1305-aead = { version = "0.1", optional = true }
blake2-rfc = { version = "0.2", optional = true }
sha2 = { version = "0.8", optional = true}
rand = { version = "0.6", optional = true }
x25519-dalek = { version = "0.5", optional = true }

# ring crypto proivder
ring = { version = "0.14", optional = true }

# hacl-star crypto provider
hacl-star = { version = "0.1.0", optional = true }

[dev-dependencies]
clap = "2"
criterion = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hex = "0.3"
lazy_static = "1.3"

[build-dependencies]
rustc_version = "0.2"

[package.metadata.docs.rs]
features = [ "ring-resolver", "hacl-star-resolver" ]
all-features = false
no-default-features = false

